// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNaG_NhTSTRldyJyS0bDI5Hcm6La4aeWE',
    appId: '1:349701023452:web:be5cfeab673751904af619',
    messagingSenderId: '349701023452',
    projectId: 'licenta-georgebardas',
    authDomain: 'licenta-georgebardas.firebaseapp.com',
    storageBucket: 'licenta-georgebardas.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu4qDk6LSNfu6jeQj0etRJkoQB7JO1rAU',
    appId: '1:349701023452:android:2e95501d0f317eb44af619',
    messagingSenderId: '349701023452',
    projectId: 'licenta-georgebardas',
    storageBucket: 'licenta-georgebardas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGWfMAzvM0piUB16quG2cdiePi7-AsAY4',
    appId: '1:349701023452:ios:cb7f02bf03013c9d4af619',
    messagingSenderId: '349701023452',
    projectId: 'licenta-georgebardas',
    storageBucket: 'licenta-georgebardas.appspot.com',
    iosClientId: '349701023452-st9q43gtqi5imhogii2n564nju7nemd5.apps.googleusercontent.com',
    iosBundleId: 'com.example.licenta',
  );
}
